project_id = "kmbcslfbhpcmxvdsokja"

[functions.admin-users]
verify_jwt = true

[functions.facebook-capi]
verify_jwt = false

[functions.facebook-feed]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.bkash-payment]
verify_jwt = false

[functions.sslcommerz-payment]
verify_jwt = false

[functions.uddoktapay-payment]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
